// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKuvRORjcyETavEqlnljlRGPiDOWsR0DI',
    appId: '1:712408194460:web:e31630efa9f246b1dffc59',
    messagingSenderId: '712408194460',
    projectId: 'hackiwhaa',
    authDomain: 'hackiwhaa.firebaseapp.com',
    storageBucket: 'hackiwhaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKDI05olIdnDWbvRtHJxBKreaVkPeCsDo',
    appId: '1:712408194460:android:6f8d651773051abcdffc59',
    messagingSenderId: '712408194460',
    projectId: 'hackiwhaa',
    storageBucket: 'hackiwhaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3-xKt29DYpNMneEPUYiiQ4u5QcuJVMT8',
    appId: '1:712408194460:ios:b02cd7d9b4f2c739dffc59',
    messagingSenderId: '712408194460',
    projectId: 'hackiwhaa',
    storageBucket: 'hackiwhaa.appspot.com',
    iosBundleId: 'com.example.hackiwha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3-xKt29DYpNMneEPUYiiQ4u5QcuJVMT8',
    appId: '1:712408194460:ios:d03c1dbda68de70fdffc59',
    messagingSenderId: '712408194460',
    projectId: 'hackiwhaa',
    storageBucket: 'hackiwhaa.appspot.com',
    iosBundleId: 'com.example.hackiwha.RunnerTests',
  );
}
